"""Generate Stata code that reproduces the paper's static tables (1, 2, A4,
A8) cell-for-cell, from the ground-truth CSVs extracted from the v34 docx.

Emits work/rrr_round2/static_blocks.do — a fragment to splice into
19_export_tables.do. Non-ASCII characters are emitted via uchar(); embedded
newlines via uchar(10). Long cells are built with chained
``replace c = c + ...`` appends so no line exceeds Stata-comfortable length.
"""
import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))
V34 = os.path.join(HERE, "v34")

TABLES = [
    ("paper_table1.csv", "table1_regime_taxonomy.csv", "Table 1"),
    ("paper_table2.csv", "table2_model_parameters.csv", "Table 2"),
    ("paper_tableA4.csv", "tableA4_facility_spec.csv", "Table A4"),
    ("paper_tableA8.csv", "tableA8_workload_classification.csv", "Table A8"),
]


def stata_parts(s):
    """Expression parts for s: ASCII chunks quoted, the rest via uchar()."""
    parts = []
    buf = ""
    for ch in s:
        if 32 <= ord(ch) < 127 and ch != '"':
            buf += ch
        else:
            if buf:
                parts.append(f'"{buf}"')
                buf = ""
            parts.append(f"uchar({ord(ch)})")
    if buf:
        parts.append(f'"{buf}"')
    return parts or ['""']


def emit_cell(out, col, row_idx, value):
    """Emit one or more replace statements building the cell value."""
    parts = stata_parts(value)
    groups = []
    cur = []
    cur_len = 0
    for p in parts:
        if cur and cur_len + len(p) > 70:
            groups.append(cur)
            cur = []
            cur_len = 0
        cur.append(p)
        cur_len += len(p) + 3
    if cur:
        groups.append(cur)
    first = True
    for g in groups:
        expr = " + ".join(g)
        if first:
            out.append(f"replace c{col} = {expr} in {row_idx}")
            first = False
        else:
            out.append(f"replace c{col} = c{col} + {expr} in {row_idx}")


def emit_table(out, paper_csv, out_csv, label):
    with open(os.path.join(V34, paper_csv), encoding="utf-8-sig",
              newline="") as f:
        rows = list(csv.reader(f))
    ncols = max(len(r) for r in rows)
    out.append("// " + "=" * 78)
    out.append(f"// {label} — mirrors the paper exhibit cell-for-cell")
    out.append("// (block generated by work/rrr_round2/gen_static_blocks.py"
               " from the docx)")
    out.append("// " + "=" * 78)
    out.append("clear")
    out.append(f"set obs {len(rows)}")
    for c in range(ncols):
        out.append(f"gen str244 c{c + 1} = \"\"")
    for r, row in enumerate(rows, 1):
        for c in range(ncols):
            val = row[c] if c < len(row) else ""
            # typographic line breaks inside cells -> spaces (Stata's
            # export delimited writes raw LFs, which split CSV records)
            val = val.replace("\r\n", "\n").replace("\n", " ")
            if val:
                emit_cell(out, c + 1, r, val)
    out.append(f'export delimited using "$output/{out_csv}", '
               "replace novarnames")
    out.append("")


def main():
    out = []
    for paper_csv, out_csv, label in TABLES:
        emit_table(out, paper_csv, out_csv, label)
    path = os.path.join(HERE, "static_blocks.do")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"wrote {path} ({len(out)} lines)")


if __name__ == "__main__":
    main()
