// ==============================================================================
// Table 1 — mirrors the paper exhibit cell-for-cell
// (block generated by work/rrr_round2/gen_static_blocks.py from the docx)
// ==============================================================================
clear
set obs 5
gen str244 c1 = ""
gen str244 c2 = ""
gen str244 c3 = ""
gen str244 c4 = ""
gen str244 c5 = ""
replace c3 = "Training domestic production cost " + uchar(8594) in 1
replace c4 = "Training domestic production cost " + uchar(8594) in 1
replace c5 = "Training domestic production cost " + uchar(8594) in 1
replace c3 = "Export" in 2
replace c4 = "Domestic" in 2
replace c5 = "Import" in 2
replace c1 = "Inference " + uchar(8592) + " domestic production cost" in 3
replace c2 = "Export" in 3
replace c3 = uchar(10003) + "  (i) EE T+I exporter Cheapest producers" in 3
replace c4 = uchar(10007) + " Prop. 4" in 3
replace c5 = uchar(10003) + "  (ii) IE Inference hub Regional low-cost hubs" in 3
replace c1 = "Inference " + uchar(8592) + " domestic production cost" in 4
replace c2 = "Domestic" in 4
replace c3 = uchar(10007) + " Prop. 4" in 4
replace c4 = uchar(10003) + "  (iv) DD Domestic High sovereignty" in 4
replace c5 = uchar(10003) + "  (iii) ID Hybrid Isolated / moderate cost" in 4
replace c1 = "Inference " + uchar(8592) + " domestic production cost" in 5
replace c2 = "Import" in 5
replace c3 = uchar(10007) + " Prop. 4" in 5
replace c4 = uchar(10007) + " Sovereignty dominates" in 5
replace c5 = uchar(10003) + "  (v) II Full importer High-cost countries" in 5
export delimited using "$output/table1_regime_taxonomy.csv", replace novarnames

// ==============================================================================
// Table 2 — mirrors the paper exhibit cell-for-cell
// (block generated by work/rrr_round2/gen_static_blocks.py from the docx)
// ==============================================================================
clear
set obs 16
gen str244 c1 = ""
gen str244 c2 = ""
gen str244 c3 = ""
gen str244 c4 = ""
replace c1 = "Parameter" in 1
replace c2 = "Symbol" in 1
replace c3 = "Value" in 1
replace c4 = "Source" in 1
replace c1 = "GPU thermal design power" in 2
replace c2 = uchar(947) in 2
replace c3 = "0.700 kW" in 2
replace c4 = "NVIDIA (2024)" in 2
replace c1 = "GPU purchase price" in 3
replace c2 = "PGPU" in 3
replace c3 = "$25,000" in 3
replace c4 = "NVIDIA (2024)" in 3
replace c1 = "GPU useful life" in 4
replace c2 = "L" in 4
replace c3 = "3 years" in 4
replace c4 = "Industry standard" in 4
replace c1 = "GPU utilization rate" in 5
replace c2 = uchar(946) in 5
replace c3 = "0.70" in 5
replace c4 = "Barroso et al. (2018)" in 5
replace c1 = "Hours per year (365.25 x 24)" in 6
replace c2 = "H" in 6
replace c3 = "8766 hr/yr" in 6
replace c4 = "Calendar" in 6
replace c1 = "Amortized hardware cost per GPU-hour" in 7
replace c2 = uchar(961) in 7
replace c3 = "$1.36/hr" in 7
replace c4 = "Derived" in 7
replace c1 = "Amortized networking cost per GPU-hour" in 8
replace c2 = uchar(951) in 8
replace c3 = "$0.15/hr" in 8
replace c4 = "Liu et al. (2023)" in 8
replace c1 = "PUE baseline (best-practice free-air cooling)" in 9
replace c2 = uchar(966) in 9
replace c3 = "1.08" in 9
replace c4 = "Google (2024)" in 9
replace c1 = "PUE temperature sensitivity per degree C" in 10
replace c2 = uchar(948) in 10
replace c3 = "0.015 per C" in 10
replace c4 = "Flucker et al. (2013)" in 10
replace c1 = "Free-cooling temperature threshold" in 11
replace c3 = "15 C" in 11
replace c4 = "Industry standard" in 11
replace c1 = "Data center facility lifetime" in 12
replace c2 = "D" in 12
replace c3 = "15 years" in 12
replace c4 = "Turner and Townsend (2025)" in 12
replace c1 = "Latency degradation per ms of RTT" in 13
replace c2 = uchar(964) in 13
replace c3 = "0.0008 per ms" in 13
replace c4 = "Calibrated" in 13
replace c1 = "Bilateral sovereignty premium" in 14
replace c3 = "Eq. (2)" in 14
replace c4 = "Bailey et al. (2017)" in 14
replace c1 = "Training share of compute demand" in 15
replace c2 = uchar(945) in 15
replace c3 = "0.50" in 15
replace c4 = "Deloitte (2025)" in 15
replace c1 = "Total global compute demand" in 16
replace c2 = "Q" in 16
replace c3 = "6" + uchar(215) + "10" + uchar(185) + uchar(8304) + " GPU-hr/yr" in 16
replace c4 = "Epoch AI (2024)" in 16
export delimited using "$output/table2_model_parameters.csv", replace novarnames

// ==============================================================================
// Table A4 — mirrors the paper exhibit cell-for-cell
// (block generated by work/rrr_round2/gen_static_blocks.py from the docx)
// ==============================================================================
clear
set obs 10
gen str244 c1 = ""
gen str244 c2 = ""
replace c1 = "Parameter" in 1
replace c2 = "Value" in 1
replace c1 = "IT capacity" in 2
replace c2 = "40 MW" in 2
replace c1 = "Total power (with cooling)" in 3
replace c2 = "43.2 MW (PUE = 1.08)" in 3
replace c1 = "GPU count" in 4
replace c2 = "57,142 (H100-class, 700W each)" in 4
replace c1 = "GPU cost / lifetime" in 5
replace c2 = "$25,000 / 3 yr (" + uchar(8722) + "10% per generation)" in 5
replace c1 = "Construction cost" in 6
replace c2 = "$313M ($7.83/W)" in 6
replace c1 = "Electricity price" in 7
replace c2 = "$0.038/kWh (+2%/yr real)" in 7
replace c1 = "Revenue price" in 8
replace c2 = "$2.00/GPU-hr (wholesale)" in 8
replace c1 = "Utilization" in 9
replace c2 = "70% steady-state (40% yr 1, 60% yr 2)" in 9
replace c1 = "WACC" in 10
replace c2 = "12.6%" in 10
export delimited using "$output/tableA4_facility_spec.csv", replace novarnames

// ==============================================================================
// Table A8 — mirrors the paper exhibit cell-for-cell
// (block generated by work/rrr_round2/gen_static_blocks.py from the docx)
// ==============================================================================
clear
set obs 6
gen str244 c1 = ""
gen str244 c2 = ""
gen str244 c3 = ""
gen str244 c4 = ""
gen str244 c5 = ""
replace c1 = "Workload" in 1
replace c2 = "Example" in 1
replace c3 = "Latency tolerance" in 1
replace c4 = "Offshorable?" in 1
replace c5 = "Model treatment" in 1
replace c1 = "Large-scale training" in 2
replace c2 = "Foundation model pre-training" in 2
replace c3 = "Days" + uchar(8211) + "weeks" in 2
replace c4 = "Fully" in 2
replace c5 = uchar(964) + uchar(7451) + " = 0" in 2
replace c1 = "Fine-tuning" in 3
replace c2 = "Domain adaptation on proprietary data" in 3
replace c3 = "Hours" in 3
replace c4 = "Mostly" in 3
replace c5 = "Treated as training" in 3
replace c1 = "Agentic inference" in 4
replace c2 = "Multi-step reasoning, tool use" in 4
replace c3 = "500" + uchar(8211) + "2,000 ms" in 4
replace c4 = "Regionally" in 4
replace c5 = "Intermediate (fn." + uchar(160) + "7)" in 4
replace c1 = "Interactive inference" in 5
replace c2 = "Chatbot, search, recommendation" in 5
replace c3 = "50" + uchar(8211) + "200 ms" in 5
replace c4 = "Limited" in 5
replace c5 = uchar(964) + uchar(7522) + " > 0, threshold l" + uchar(772) in 5
replace c1 = "Real-time control" in 6
replace c2 = "Autonomous vehicles, robotics" in 6
replace c3 = "< 20 ms" in 6
replace c4 = "No" in 6
replace c5 = "Domestic only" in 6
export delimited using "$output/tableA8_workload_classification.csv", replace novarnames
